#!/bin/bash

# Встановлення gitleaks і pre-commit hook, якщо не встановлено
if ! command -v gitleaks &> /dev/null || [[ ! -f .git/hooks/pre-commit ]]
then
    echo "Встановлення необхідних компонентів..."
    ./install_gitleaks.sh
    if [[ $? -ne 0 ]]; then
        echo "Помилка встановлення необхідних компонентів."
        exit 1
    fi
fi

# Перевірка чи ввімкнено pre-commit hook
if [[ "$(git config hooks.gitleaks.enable)" != "true" ]]; then
    echo "gitleaks pre-commit hook вимкнено. Для ввімкнення використайте: git config hooks.gitleaks.enable true"
    exit 0
fi

# Запуск gitleaks з виведенням детальної інформації та перевіркою staged файлів
echo "Запуск gitleaks..."
git diff --cached --name-only | xargs gitleaks detect --no-git --source

# Перевірка результату виконання gitleaks
if [[ $? -ne 0 ]]; then
    echo "gitleaks виявив секрети у вашому коді. Коміт відхилено."
    exit 1
else
    echo "gitleaks не виявив секретів. Коміт дозволено."
    exit 0
fi
